spring:
  application:
    name: busbookingservice
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/busroutemangementdb
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  cloud:
    config:
      uri:
      - http://localhost:8888
  config:
    import: configserver:http://localhost:8888
  
server:
  port: 8083
  servlet:
    context-path: "/busbooking"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
  instance:
    preferIpAddress: true
    
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
